quarkus:
  http:
    port: 9000
  rest-client:
    recommend-api:
      url: http://190.92.244.220:8088/api
      scope: singleton
  resteasy-json:
    json-default: false
  smallrye-openapi:
    enable: true
    path: /swagger
  datasource:
    db-kind: mysql
    username: root
    password: 123456
    jdbc:
      url: jdbc:mysql://localhost:3306/github?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
