quarkus:
  http:
    port: 9000
  rest-client:
    recommend-api:
      url: ${RECOMMEND_API}
      scope: singleton
  resteasy-json:
    json-default: false
  smallrye-openapi:
    enable: true
    path: /swagger
  datasource:
    db-kind: mysql
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_DSN}
