quarkus:
  http:
    port: 9000
    cors:
      origins: "*"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
  rest-client:
    recommend-api:
      url: ${RECOMMEND_API}
      scope: singleton
  smallrye-openapi:
    enable: true
    path: /swagger
  datasource:
    db-kind: mysql
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_DSN}
