name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable
        uses: maxday/quarkus-native-build-docker-action@13bf5c4ae6942143cf43a5663a6c7f847ac3163c
        with:
          outputName: app-runner
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: app-runner

  dockerize:
    runs-on: ubuntu-latest
    name: Embed the native executable in a Docker container
    needs: native_build
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Download the binary
        uses: actions/download-artifact@v1
        with:
          name: native-executable
      - name: Dockerize
        id: dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: quarkus-recommender
          executablePath: native-executable/app-runner
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_REPO_USER }} --password=${{ secrets.DOCKER_REPO_PASSWORD }}
      - name: Docker Push
        run: docker push quarkus-recommender

