name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Download the binary
        uses: actions/download-artifact@v1
        with:
          name: native-executable

      - name: Dockerize
        id: dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: quarkus-recommender
          executablePath: native-executable/app-runner

      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_REPO_USER }} --password=${{ secrets.DOCKER_REPO_PASSWORD }}

      - name: Docker Push
        run: docker push quarkus-recommender

